import { Project } from '../types/project';
import { VersionRecord, VersionType } from '../types/version';

export const INITIAL_MOCK_PROJECTS: Project[] = [
  { id: 1, name: 'Core API Backend', code: 'CAB', description: 'Central microservices backend platform' },
  { id: 2, name: 'Web Dashboard', code: 'WDB', description: 'React single-page client application' },
  { id: 3, name: 'Mobile iOS App', code: 'MIA', description: 'Native Swift iOS application' },
  { id: 4, name: 'DevOps Pipeline', code: 'DOP', description: 'CI/CD automation scripts & manifests' },
];

export const INITIAL_MOCK_VERSIONS: VersionRecord[] = [
  {
    id: 101,
    projectId: 1,
    projectName: 'Core API Backend',
    version: 'major',
    versionNumber: 'v1.0.0',
    versionTitle: 'Initial Production Release',
    versionInfo: { author: 'Lead Architect', changes: ['Auth System', 'Database Migration', 'Rate Limiting'], status: 'stable' },
    isActive: true,
    createdBy: 1,
    createdAt: '2026-06-15T10:30:00Z',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 102,
    projectId: 1,
    projectName: 'Core API Backend',
    version: 'minor',
    versionNumber: 'v1.1.0',
    versionTitle: 'Added User Roles & Permissions',
    versionInfo: { author: 'Backend Dev', changes: ['RBAC Middleware', 'JWT Refresh Token Fix'], status: 'active' },
    isActive: true,
    createdBy: 1,
    createdAt: '2026-07-01T14:20:00Z',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 103,
    projectId: 2,
    projectName: 'Web Dashboard',
    version: 'major',
    versionNumber: 'v1.0.0',
    versionTitle: 'Dashboard V1 Launch',
    versionInfo: { UI: 'Vite + React TS', theme: 'Dark Mode Glassmorphism' },
    isActive: true,
    createdBy: 2,
    createdAt: '2026-07-10T08:45:00Z',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 104,
    projectId: 2,
    projectName: 'Web Dashboard',
    version: 'bug-fix',
    versionNumber: 'v1.0.1',
    versionTitle: 'Fixed Refresh Token Interceptor Loop',
    versionInfo: { fix: 'Axios 401 retry queue handler', issueId: 'VC-402' },
    isActive: true,
    createdBy: 2,
    createdAt: '2026-07-18T11:10:00Z',
    updatedBy: 2,
    updatedAt: '2026-07-18T11:15:00Z',
  },
  {
    id: 105,
    projectId: 3,
    projectName: 'Mobile iOS App',
    version: 'major',
    versionNumber: 'v2.0.0',
    versionTitle: 'SwiftUI Redesign',
    versionInfo: { build: 200, targetOS: 'iOS 17+' },
    isActive: false, // Soft deleted record example
    createdBy: 3,
    createdAt: '2026-05-20T16:00:00Z',
    updatedBy: 1,
    updatedAt: '2026-07-22T09:30:00Z',
  },
  {
    id: 106,
    projectId: 4,
    projectName: 'DevOps Pipeline',
    version: 'bug-fix',
    versionNumber: 'v0.9.1',
    versionTitle: 'Updated Kubernetes Helm Chart Spec',
    versionInfo: { env: 'production', cluster: 'k8s-east-1' },
    isActive: true,
    createdBy: 4,
    createdAt: '2026-07-25T13:00:00Z',
    updatedBy: null,
    updatedAt: null,
  },
];
